name: Trigger auto deployment for tinboost

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/tinboost-AutoDeployTrigger-c6911a08-5d0b-4b69-af94-7aaf738b10b8.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TINBOOST_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TINBOOST_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TINBOOST_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: tindboosts.azurecr.io
          registryUsername: ${{ secrets.TINBOOST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TINBOOST_REGISTRY_PASSWORD }}
          containerAppName: tinboost
          resourceGroup: rg-cont
          imageToBuild: tindboosts.azurecr.io/tinboost:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


